---
title: "OPUS Stimulus Norming"
author: "Natalia Vélez"
date: "March 12, 2015"
output: html_document
---

**Step 1:** Cleaning up & processing data
```{r Load data, warning=FALSE,message=FALSE}
# Load libraries
library(dplyr)
library(tidyr)
```

```{r}
# Load raw data
k <- read.csv("movie_key.csv")
d <- read.csv("opus_norming.csv") %>%
  mutate(appeal = appeal - 13)
d <- cbind(d, k[match(d$movie, k$title),2:4])
```

**Step 2:** Summarizing data
```{r Data summary}
# Helper function: computes standard error of the mean
sem <- function(x) {return(sd(x)/sqrt(length(x)))}

# Create data summary
d.summ <- d %>%
  group_by(workerID, valence, setting, genre) %>%
  gather(feature, rating, action:sad) %>%
  arrange(workerID, movie_no) %>%
  group_by(workerID, valence, setting, genre, feature) %>%
  summarise(avg_rating = mean(rating, na.rm = T)) %>%
  group_by(valence, setting, genre, feature) %>%
  summarise(rating = mean(avg_rating),
            se = sem(avg_rating))

#### Beginner's note: ####
# The %>% operand 'pipes' the result of one command to the next command. It's a really nice way of chaining commands
# together. Compare the block of code above to the one below, with no piping, which produces the same result. It's
# clunky and doesn't make for very readable code, but take advantage of the step-by-step breakdown below to
# really understand what each command is doing. Remember to use the ? symbol (e.g., ?group_by) on your console
# to check out what different functions do and what arguments they take.
#########################

d.clunky <- group_by(d, workerID, valence, setting, genre)
d.clunky <- gather(d.clunky, feature, rating, action:sad)
d.clunky <- arrange(d.clunky, workerID, movie_no)
d.clunky <- group_by(d.clunky, workerID, valence, setting, genre, feature)
d.clunky <- summarise(d.clunky, avg_rating = mean(rating, na.rm = T))
d.clunky <- group_by(d.clunky, valence, setting, genre, feature)
d.clunky <- summarise(d.clunky, rating = mean(avg_rating),
                      se = sem(avg_rating))

# Plot data summary
library(ggplot2)
ggplot(d.summ, aes(x = valence, y = rating, fill = interaction(setting, genre))) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(width = 0.1, position = position_dodge(width = 0.9),
                aes(ymin = rating - se, ymax = rating + se)) +
  facet_wrap(~ feature, ncol = 3) +
  coord_cartesian(NULL, c(1,7)) +
  scale_fill_manual(name = "Genre",
                    breaks = c("period.action", "scifi.action", "period.romance", "scifi.romance"),
                    labels = c("Historical action", "Sci-fi action", 
                               "Historical romance", "Sci-fi romance"),
                    values = c("#E8670C", "#A14373", "#FEA154", "#e5558f"))
```

**Step 3:** Correlational analysis
```{r Correlations}
```

**Step 4:** Item analysis
```{r Item analysis, fig.width = 9, fig.height = 6}
d.item <- d %>%
  gather(feature, rating, action:sad) %>%
  group_by(movie, valence, setting, genre, feature) %>%
  summarise(mean_rating = mean(rating, na.rm = T),
            se_rating = sd(rating, na.rm = T)/sqrt(length(na.omit(rating))))

# # Positive
# temp = d.item[order(d.item$valence),]
# temp$movie = factor(temp$movie, levels = unique(temp$movie))
# ggplot(temp[temp$feature == "happy",], aes(x = movie, y = mean_rating, colour = valence)) +
#   geom_point() +
#   geom_hline(aes(yintercept=4)) +
#   coord_cartesian(NULL, c(1,7)) +
#   coord_flip(ylim = c(1:7)) +
#   ggtitle("Happy")
# 
# # Negative
# temp = d.item[order(d.item$valence),]
# temp$movie = factor(temp$movie, levels = unique(temp$movie))
# ggplot(temp[temp$feature == "sad",], aes(x = movie, y = mean_rating, colour = valence)) +
#   geom_point() +
#   geom_hline(aes(yintercept=4)) +
#   coord_cartesian(NULL, c(1,7)) +
#   coord_flip(ylim = c(1:7)) +
#   ggtitle("Sad")


# Positive + Negative
temp = d.item[order(d.item$valence),]
temp$movie = factor(temp$movie, levels = unique(temp$movie))
ggplot(temp[temp$feature == "happy" | temp$feature == "sad",], aes(x = movie, y = mean_rating, colour = valence)) + facet_grid(. ~ feature) +
  geom_point() +
  geom_hline(aes(yintercept=4)) +
  coord_cartesian(NULL, c(1,7)) +
  coord_flip(ylim = c(1:7)) +
    geom_errorbar(width = 0.1, position = position_dodge(width = 0.9),
                aes(ymin = mean_rating - se_rating, ymax = mean_rating + se_rating))
```

Problematic happy movies = Railroad station, rise of the people, independence of norway, gold-seeker.

```{r fig.width = 9, fig.height = 6}
# Scifi + Historical
temp = d.item[order(d.item$setting),]
temp$movie = factor(temp$movie, levels = unique(temp$movie))
ggplot(temp[temp$feature == "scifi" | temp$feature == "historical",], aes(x = movie, y = mean_rating, colour = setting)) + facet_grid(. ~ feature) +
  geom_point() +
  geom_hline(aes(yintercept=4)) +
  coord_cartesian(NULL, c(1,7)) +
  coord_flip(ylim = c(1:7)) +
    geom_errorbar(width = 0.1, position = position_dodge(width = 0.9),
                aes(ymin = mean_rating - se_rating, ymax = mean_rating + se_rating))
```

```{r fig.width = 9, fig.height = 6}
# Action + Romance
temp = d.item[order(d.item$genre),]
temp$movie = factor(temp$movie, levels = unique(temp$movie))
ggplot(temp[temp$feature == "action" | temp$feature == "romance",], aes(x = movie, y = mean_rating, colour = genre)) + facet_grid(. ~ feature) +
  geom_point() +
  geom_hline(aes(yintercept=4)) +
  coord_cartesian(NULL, c(1,7)) +
  coord_flip(ylim = c(1:7)) +
  geom_errorbar(width = 0.1, position = position_dodge(width = 0.9),
                aes(ymin = mean_rating - se_rating, ymax = mean_rating + se_rating))
```

Negative Scifi Romance is the other problematic category (Quarantined, the flood, lab rats)



```{r}
# Bonus points:
# 1) Changing the legend title and labels
# 2) Saving the plot to an image file
# 3) Changing the x and y axis labels
# 4) Alphabetizing movie labels
# 5) Adding error bars (ymin = mean_rating - se_rating, ymax = mean_rating + se_rating)

```